In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, Activation, Dropout
from tensorflow.keras.layers import Conv1D, MaxPooling1D, GlobalMaxPooling1D
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from pandas import read_excel

In [ ]:
from google.colab import files
fileku = files.upload()

Saving DatasetTweet.csv to DatasetTweet.csv


In [ ]:
df = pd.read_csv('DatasetTweet.csv')
df.head()

sentimen                                              Tweet
0         2  lagu bosan apa yang aku save ni huhuhuhuhuhuhu...
1         2  kita lanjutkan saja diam ini hingga kau dan ak...
2         1  doa rezeki tak putus inna haa zaa larizquna ma...
3         1  makasih loh ntar kita bagi hasil aku 99 9 sisa...
4         2  aku tak faham betul jenis orang malaysia yang ...

In [ ]:
text = df["Tweet"].tolist()
print(text)

['lagu bosan apa yang aku save ni huhuhuhuhuhuhuhuhuhuuuuuuuuuuuuuu', 'kita lanjutkan saja diam ini hingga kau dan aku mengerti tidak semua kebersamaan harus melibatkan hati ', 'doa rezeki tak putus inna haa zaa larizquna maa lahu min na fadesungguhnya ini ialah pemberian kami kepada kamu p ', 'makasih loh ntar kita bagi hasil aku 99 9 sisanya buat kamu', 'aku tak faham betul jenis orang malaysia yang tak reti nak sangkut balik hose tu aku geli bodoh nak pegang ', 'barusan liat tulisan di belakang truk rela injek kopling demi kamu bisa shopping ', 'cerita dia macam ni mamat ni hari2 aku nampak keluar masuk cimb ceria ja tapi hari ni aku tengok muka dia masam aku p ', 'ya aku akan menjadi satu satunya bukan nomor satu tetapi satu satunya', "aku aja capek sama diriku sendiri apalagi kamu maaf ya ' ", 'aku cuba nak amalkan sikap pergi mampus tapi sayang aku gagal sebab aku jenis mudah kesian dan mudah memaafkan ', 'her itu lho miss kevin sama keven rebutan gimbot ya wis aku beli 2 ae samb

In [ ]:
y = df['sentimen']
y = to_categorical(y)
print(y)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [ ]:
df['sentimen'].value_counts()

0    5327
2    2887
1    2592
Name: sentimen, dtype: int64

In [ ]:
token = Tokenizer()
token.fit_on_texts(text)

In [ ]:
token.index_word

{1: 'aku',
 2: 'kamu',
 3: 'yang',
 4: 'dan',
 5: 'kita',
 6: 'yg',
 7: 'di',
 8: 'ada',
 9: 'tak',
 10: 'ini',
 11: 'apa',
 12: 'orang',
 13: 'dia',
 14: 'ni',
 15: 'ya',
 16: 'itu',
 17: 'tapi',
 18: 'nak',
 19: 'mereka',
 20: 'ke',
 21: 'untuk',
 22: 'mau',
 23: 'kalau',
 24: 'juga',
 25: 'bisa',
 26: 'dari',
 27: 'dengan',
 28: 'jadi',
 29: 'lagi',
 30: 'kau',
 31: 'buat',
 32: 'sama',
 33: 'tu',
 34: 'aja',
 35: 'ga',
 36: 'akan',
 37: 'tidak',
 38: 'dah',
 39: 'jangan',
 40: 'kalo',
 41: 'gak',
 42: 'hari',
 43: 'bukan',
 44: 'dalam',
 45: 'je',
 46: 'boleh',
 47: 'semua',
 48: 'pernah',
 49: 'masih',
 50: 'suka',
 51: 'kan',
 52: 'karena',
 53: 'pun',
 54: 'baik',
 55: 'lebih',
 56: 'tau',
 57: 'allah',
 58: 'mana',
 59: 'saya',
 60: 'baru',
 61: 'bila',
 62: 'lah',
 63: 'adalah',
 64: 'banyak',
 65: 'lain',
 66: 'nanti',
 67: 'nya',
 68: 'la',
 69: 'dulu',
 70: 'harus',
 71: 'udah',
 72: 'hati',
 73: 'sudah',
 74: 'punya',
 75: 'jika',
 76: 'batik',
 77: 'pada',
 78: 'macam',
 

In [ ]:
vocab = len(token.index_word)+1
vocab

22710

In [ ]:
x = ['aku lagi galau nih']
token.texts_to_sequences(x)

[[1, 29, 2699, 122]]

In [ ]:
encode_text = token.texts_to_sequences(text)

In [ ]:
max_kata = 100
X = pad_sequences(encode_text, maxlen = max_kata, padding="post")
X

array([[  434,  1051,    11, ...,     0,     0,     0],
       [    5,  4557,   110, ...,     0,     0,     0],
       [  291,   538,     9, ...,     0,     0,     0],
       ...,
       [  325,     6,   317, ...,     0,     0,     0],
       [  126,   222,    21, ...,     0,     0,     0],
       [  140,    57, 22709, ...,     0,     0,     0]], dtype=int32)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=40, test_size=0.3, stratify=y)

In [ ]:
X_train = np.asarray(X_train)
X_test = np.asarray(X_test)
y_train = np.asarray(y_train)
y_test = np.asarray(y_test)

In [ ]:
vec_size = 300
model = Sequential()
model.add(Embedding(vocab, vec_size, input_length=max_kata))
model.add(Conv1D(64,8, activation="relu"))
model.add(MaxPooling1D(2))
model.add(Dropout(0.5))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(16, activation='relu'))
model.add(GlobalMaxPooling1D())
model.add(Dense(3, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 100, 300)          6813000   
                                                                 
 conv1d (Conv1D)             (None, 93, 64)            153664    
                                                                 
 max_pooling1d (MaxPooling1D  (None, 46, 64)           0         
 )                                                               
                                                                 
 dropout (Dropout)           (None, 46, 64)            0         
                                                                 
 dense (Dense)               (None, 46, 32)            2080      
                                                                 
 dropout_1 (Dropout)         (None, 46, 32)            0         
                                                        

In [ ]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=100, validation_data=(X_test, y_test))  

Epoch 1/100
237/237 [==============================] - 42s 173ms/step - loss: 1.0481 - accuracy: 0.4903 - val_loss: 1.0597 - val_accuracy: 0.4929
Epoch 2/100
237/237 [==============================] - 40s 168ms/step - loss: 1.0033 - accuracy: 0.5156 - val_loss: 0.9629 - val_accuracy: 0.5555
Epoch 3/100
237/237 [==============================] - 40s 170ms/step - loss: 0.7726 - accuracy: 0.6713 - val_loss: 0.9209 - val_accuracy: 0.5787
Epoch 4/100
237/237 [==============================] - 40s 169ms/step - loss: 0.4798 - accuracy: 0.8256 - val_loss: 0.9514 - val_accuracy: 0.5824
Epoch 5/100
237/237 [==============================] - 40s 169ms/step - loss: 0.2948 - accuracy: 0.9019 - val_loss: 1.0781 - val_accuracy: 0.5783
Epoch 6/100
237/237 [==============================] - 40s 168ms/step - loss: 0.2186 - accuracy: 0.9352 - val_loss: 1.1433 - val_accuracy: 0.5756
Epoch 7/100
237/237 [==============================] - 40s 167ms/step - loss: 0.1767 - accuracy: 0.9466 - val_loss: 1.1875 -

In [ ]:
def get_encode(x):
  x = token.texts_to_sequences(x)
  x = pad_sequences(x, maxlen = max_kata, padding="post")
  return x

In [ ]:
x = ["ga jelas banget videonya, suaranya kecil, unsubscribelah"]
x = get_encode(x)

In [ ]:
predict_x=model.predict(x) 
classes_x=np.argmax(predict_x,axis=1)
classes_x

array([2])